### ISSUE TITLE
Instances Mapping to kubernetes_host

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-kubernetes-provider#12]
Currently Instances are mapped to nodes in the cluster blueprint of node type "kubernetes_host".[Ref](https://github.com/cloudify-incubator/cloudify-kubernetes-provider/blob/56017e1a2ad707af834a59bee5c6a9d51fb5a074/src/cloudifyprovider/instances.go#L49)

The problem with this approach is that the node type needs to be redefined for each cluster deployment, examples:
- https://github.com/cloudify-incubator/cloudify-kubernetes-provider/blob/56017e1a2ad707af834a59bee5c6a9d51fb5a074/examples/cluster_blueprint/aws.yaml#L34
- https://github.com/cloudify-incubator/cloudify-kubernetes-provider/blob/56017e1a2ad707af834a59bee5c6a9d51fb5a074/examples/cluster_blueprint/azure.yaml#L48

On the one hand, since a Kubernetes Node is strictly speaking a machine, the direct corresponding type in cloudify is cloudify.nodes.Compute`. On the other hand, a Kubernetes Node should also have several capabilities that are not part of Cloudify Compute nodes - container runtime, kube-proxy, etc.

I want to propose an alternative:

A new node type that is "contained_in" a Cloudify Compute node that represents the Kubernetes Node, such as:

```yaml
node_types:
    cloudify.nodes.Kubernetes.Node:
        derived_from: cloudify.nodes.SoftwareComponent
        properties: {}
node_templates:
    kube_node:
        type: cloudify.nodes.Kubernetes.Node
        relationships:
        - type: cloudify.relationships.contained_in
           target: some_vm
```
